### PR TITLE
Add {UUID-} placeholder

### LINKED ISSUE #4: add placeholder like "{UUID-}"
some API prefer UUID without "-"，can u just add a placeholder like {UUID-} which returns a UUID without "-",i saw [BlueMapSkinIntegration](https://github.com/Cerothen/BlueMapSkinIntegration) has that, but it cant load on the server without SkinsRestorer installed,which isn't needed for URL source. thx

### PR DESCRIPTION
**Pull request by XenWayne**

### CODE REVIEW

**Comment by XenWayne** [comment]
#4

**Comment by TechnicJelle** [comment]
If you add this placeholder in the config https://github.com/TechnicJelle/BlueMapCustomSkinProvider/blob/main/src/main/resources/config.yml and explain what it does there, then I'll merge this :+1: 

I feel the current two placeholders are self-explanatory enough but "`{UUID-}`" is less so

**Comment by XenWayne** [comment]
So I added a description of `{UUID-}` in the latest commit : )

**Comment by TechnicJelle** [comment]
Yep, I just tested it locally and it works.
Thank you for this contribution!

**Comment by TechnicJelle** [comment]
If I might ask, though, could you give an example of one such skin API that doesn't support dashes in the UUID? I'm kind of curious now. I've only really ever worked with Minotar and Crafatar, myself. And both of those support normal dashed UUIDs.

**Comment by XenWayne** [comment]
ok,I can explain that，so basically I'm testing a local skinserver which stores skin files locally.As we all know,dashed UUID is hard to index for database,especially for large amounts of data,so the primary key in the database is the UUID without dashes.The API is also implemented in this style,thouth it can be solved by changing API design,it's easier to change the way to request :)

If you are interested, feel free to visit the [document](https://docs.mualliance.cn/dev/union/auth) for the whole project,(well that is writen in Chinese,Sorry for the inconvenience)

**Pull request merged**
